//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSINotification.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppConfiguration
    {
        public long ConfigID { get; set; }
        public string KeyName { get; set; }
        public string Value { get; set; }
        public long StatusID { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
    }
}
