//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSINotification.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailNotification
    {
        public int EmailNotificationID { get; set; }
        public string Subject { get; set; }
        public string MailContent { get; set; }
        public string AttachedFileName { get; set; }
        public string Receipent { get; set; }
        public int EmailSendStatus { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public string Comment { get; set; }
    }
}
